### ISSUE TITLE
Problem with .net45 dlls for Thycotic SDK

### ISSUE THREAD

**Issue by LadaVarga** [thycotic/sdk-documentation#17]
Hello,

We have a similar problem  as in https://github.com/thycotic/sdk-documentation/issues/7 
We use ThycoticSDK 1.4.1 or 1.5.0 and net45 dlls.

Where it is failing:
`  client.Configure(new ConfigSettings
            {
                SecretServerUrl = "",
                RuleName = "",
                RuleKey = "",
                CacheStrategy = CacheStrategy.Never,    
                CacheAge = 0,
                ResetToken = Guid.NewGuid().ToString()
            });
        }`
Exception:

▶ | $exception | {"Object reference not set to an instance of an object."} | System.NullReferenceException

   at Thycotic.SecretServer.Sdk.Extensions.Integration.Clients.SecretServerClient.ProcessCreateResponse(ApiResponse`1 response)
   at Thycotic.SecretServer.Sdk.Extensions.Integration.Clients.SecretServerClient.Configure(IConfigSettings settings, Boolean force)
   at Sxxxx..ctor() in C:\xxxx\Secrets.cs:line 24

Strange is that with nestandard 2.0 dll it is ok (we have another .netcore project where we use it and it is ok we can pass this stage)

In this project we cannot use .netcore.

Is there problem with some dependencies? Have you seen this problem?

Lada Varga
SolarWinds

**Comment by LadaVarga** [comment]
Hello,

After a couple of hours of investigation, I've figured out the ApiResponse returns fail. Could you please improve this behavior and instead of unknown "Object reference not set to an instance of an object." return proper error code wit proper message. It is really hard to get the proper root cause (bad credentials, bad request, bad address).

**Comment by ncraig419** [comment]
same issue, 
private void ProcessCreateResponse(ApiResponse<SdkClientAccountModel> response)
    {
      if (!((ApiResponse) response).get_IsSuccessStatusCode())
        this._sdkClientConfigProvider.RemoveConfigurations();
<MISSING A RETURN OR EXCEPTIONTHROW HERE. Either way, this should not continue.>
      ClientCredentials clientCredentials = new ClientCredentials();
      clientCredentials.set_ClientId("sdk-client-" + response.get_Model().get_ClientId());
      clientCredentials.set_ClientSecret(response.get_Model().get_ClientSecret());
      this._sdkClientConfigProvider.SaveCredentials(clientCredentials);
    }

**Comment by LadaVarga** [comment]
In my case issue was not properly set TLS12, after adding one line it was ok. I had to debug through your dll to get proper failure code.

**Comment by AustinBrownMCU** [comment]
I have been having the same trouble that LadaVarga describes above. The error I am receiving states:

> System.NullReferenceException: 'Object reference not set to an instance of an object.'

This exception is raised at:
`                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                var tssClient = new SecretServerClient();
                tssClient.Configure(new ConfigSettings
                {
                    SecretServerUrl = "<URI>",
                    RuleName = "<RULENAME>",
                    RuleKey = "<RULEKEY>",
                    CacheStrategy = CacheStrategy.CacheThenServerAllowExpired,
                    CacheAge = 240,
                    ResetToken = Guid.NewGuid().ToString()
                });`
I have not been able to track down where my issue lies. I have been able to use the RestAPI via powershell without issue, but the error handling in this SDK has been a little tough to manage.

**Comment by dbloch3643** [comment]
I'm having similar issue, with .Net 5.0 works. now using it with .Net 4.6.1 I'm getting the Object Reference error during the .Configure Method within the SDK
